// Phase 9, Slice E — audit export content/format.
//
// Proves the rich content (metadata, posture, requirements-in-force, event trail, documents
// manifest), tenant_offboard from-inception completeness, the District export path, and the
// includes_sensitive INVERSE (default omits Sensitive; opt-in includes it).

import fs from 'fs';
import path from 'path';
import { randomUUID } from 'crypto';
import type Database from 'better-sqlite3';
import {
  seedTenant, seedTenantUser, seedRegion, seedLocation, seedVendor, seedVendorLocation,
  seedDocument, seedExtraction, seedRequirementSettings, seedRequirementRule, assignUserToRegion,
} from './helpers';
import { getRawDb, closeDb } from '@/lib/db/client';
import { TenantDB } from '@/lib/db/tenant';
import { issueToken } from '@/lib/auth/jwt';
import { encryptField } from '@/lib/crypto/field';
import { gatherAuditExportContent } from '@/lib/exports/content';
import { processQueuedExports } from '@/lib/exports/worker';
import type { FieldValue, ProcessedW9Extraction, ProcessedACHExtraction } from '@/lib/extraction/types';

const TIN = '123-45-6789', ROUTING = '021000021', ACCOUNT = '9876543210';
const SSN = /\b\d{3}-\d{2}-\d{4}\b/;
const NOW = new Date('2026-06-30T12:00:00.000Z');

function migrate(db: Database.Database): void {
  const dir = path.join(process.cwd(), 'src', 'migrations');
  db.exec(`CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)`);
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.sql')).sort()) db.exec(fs.readFileSync(path.join(dir, f), 'utf-8'));
}
function fv<T>(v: T): FieldValue<T> { return { value: v, confidence: 1, band: 'high', source: { page: 1, snippet: '' }, corroborated: false }; }
function w9(c: string): ProcessedW9Extraction { return { doc_type: 'w9', document_type_confirmed: 'w9', legal_name: fv<string | null>('Acme'), business_name: fv<string | null>('Acme'), federal_tax_classification: fv<string | null>('llc'), tin_type: fv<string | null>('ein'), tin_value: fv<string | null>(c), address: fv<string | null>('1 Main'), signature_present: fv<boolean | null>(true), signature_date: fv<string | null>('2026-01-01') }; }
function ach(r: string, a: string): ProcessedACHExtraction { return { doc_type: 'ach', document_type_confirmed: 'ach', account_holder_name: fv<string | null>('Acme'), bank_name: fv<string | null>('Bank'), routing_number: fv<string | null>(r), account_number: fv<string | null>(a), account_type: fv<string | null>('checking'), voided_check_present: fv<boolean | null>(true), authorization_signature: fv<boolean | null>(true) }; }
function aevt(db: Database.Database, tenantId: string, vendorId: string, type: string, at: Date): void {
  db.prepare(`INSERT INTO audit_events (id, tenant_id, actor_type, actor_id, event_type, target_type, target_id, payload_json, created_at) VALUES (?,?,'user','u',?,'vendor',?,'{}',?)`)
    .run(randomUUID(), tenantId, type, vendorId, at.toISOString());
}

function vendorWorld() {
  closeDb();
  const db = getRawDb();
  migrate(db);
  const t = seedTenant(db, { name: 'Storage Star' });
  const admin = seedTenantUser(db, t.id, { role: 'admin', name: 'Ada Admin' });
  const loc = seedLocation(db, t.id, { name: 'Main St' });
  const v = seedVendor(db, t.id, { business_name: 'Acme Plumbing', trade: 'plumbing' });
  seedVendorLocation(db, t.id, v.id, loc.id, { status: 'approved' });
  seedRequirementSettings(db, t.id);
  seedRequirementRule(db, t.id, admin.id, { requirement_key: 'coverage.general_liability.each_occurrence', required_value: '1000000' });
  const w9d = seedDocument(db, t.id, v.id, { doc_type: 'w9' }); seedExtraction(db, t.id, w9d.id, w9(encryptField(TIN)));
  const achd = seedDocument(db, t.id, v.id, { doc_type: 'ach' }); seedExtraction(db, t.id, achd.id, ach(encryptField(ROUTING), encryptField(ACCOUNT)));
  aevt(db, t.id, v.id, 'vendor.approved', new Date(NOW.getTime() - 86_400_000));
  return { db, t, vendorId: v.id, admin };
}

afterEach(() => closeDb());

// ── Content structure ─────────────────────────────────────────────────────────────────

describe('audit export content — structure', () => {
  test('vendor scope content has metadata, posture, requirements, events, documents', () => {
    const w = vendorWorld();
    const c = gatherAuditExportContent(w.db, w.t.id, {
      scope: 'vendor', scopeRef: w.vendorId, includesSensitive: false, generatedAt: NOW.toISOString(),
      generator: { id: w.admin.id, name: 'Ada Admin', role: 'admin' },
    });
    expect(c.metadata.find((m) => m.label === 'Scope')!.value).toContain('vendor');
    expect(c.metadata.find((m) => m.label === 'Generated by')!.value).toContain('Ada Admin');
    expect(c.metadata.find((m) => m.label === 'Sensitive data included')!.value).toBe('no');
    expect(c.posture.find((p) => p.metric === 'Approved')!.value).toBe('1');
    expect(c.requirements.some((r) => r.requirement.includes('general_liability'))).toBe(true);
    expect(c.events.some((e) => e.event_type === 'vendor.approved')).toBe(true);
    expect(c.documents.length).toBe(2); // w9 + ach on file
    expect(c.documents.every((d) => d.sensitive === '')).toBe(true); // meta only by default
  });
});

// ── includes_sensitive inverse ──────────────────────────────────────────────────────────

describe('audit export content — includes_sensitive inverse', () => {
  test('default omits Sensitive; opt-in includes the decrypted TIN/ACH in the manifest', () => {
    const w = vendorWorld();
    const base = { scope: 'vendor' as const, scopeRef: w.vendorId, generatedAt: NOW.toISOString(), generator: { id: w.admin.id, name: 'Ada', role: 'admin' } };

    const excluded = gatherAuditExportContent(w.db, w.t.id, { ...base, includesSensitive: false });
    const exclStr = JSON.stringify(excluded);
    expect(exclStr).not.toContain(TIN);
    expect(exclStr).not.toContain(ROUTING);
    expect(exclStr).not.toMatch(SSN);

    const included = gatherAuditExportContent(w.db, w.t.id, { ...base, includesSensitive: true });
    const inclStr = JSON.stringify(included);
    expect(inclStr).toContain(TIN);       // opt-in really opts in
    expect(inclStr).toContain(ROUTING);
    expect(inclStr).toContain(ACCOUNT);
    expect(included.metadata.find((m) => m.label === 'Sensitive data included')!.value).toBe('YES');
  });
});

// ── tenant_offboard completeness ────────────────────────────────────────────────────────

describe('audit export content — tenant_offboard from inception', () => {
  test('includes every tenant audit event (old + recent)', () => {
    const w = vendorWorld();
    // an ancient event from near tenant inception
    aevt(w.db, w.t.id, w.vendorId, 'vendor.invited', new Date('2019-01-01T00:00:00Z'));
    const c = gatherAuditExportContent(w.db, w.t.id, { scope: 'tenant_offboard', scopeRef: null, includesSensitive: false, generatedAt: NOW.toISOString(), generator: null });
    const allCount = (w.db.prepare('SELECT COUNT(*) n FROM audit_events WHERE tenant_id=?').get(w.t.id) as { n: number }).n;
    expect(c.events.length).toBe(allCount);
    expect(c.events[0].created_at.startsWith('2019')).toBe(true); // chronological, from inception
  });
});

// ── District export path (route) ────────────────────────────────────────────────────────

describe('audit export — District authority', () => {
  function districtWorld() {
    closeDb();
    const db = getRawDb();
    migrate(db);
    const t = seedTenant(db);
    const admin = seedTenantUser(db, t.id, { role: 'admin' });
    const district = seedTenantUser(db, t.id, { role: 'district_manager' });
    const r1 = seedRegion(db, t.id, 'R1'); const r2 = seedRegion(db, t.id, 'R2');
    assignUserToRegion(db, district.id, r1.id, t.id);
    const l1 = seedLocation(db, t.id, { regionId: r1.id });
    const v = seedVendor(db, t.id); seedVendorLocation(db, t.id, v.id, l1.id, { status: 'approved' });
    return { db, t, r1: r1.id, r2: r2.id, districtJwt: issueToken({ sub: district.id, tenantId: t.id, role: 'district_manager', type: 'tenant' }) };
  }
  async function post(jwt: string, body: unknown) {
    return (await import('@/app/api/exports/route')).POST(new Request('http://t/api/exports', { method: 'POST', headers: { Authorization: `Bearer ${jwt}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }));
  }
  function violations(db: Database.Database, tenantId: string): number {
    return (db.prepare(`SELECT COUNT(*) n FROM audit_events WHERE tenant_id=? AND event_type='security.scope_violation'`).get(tenantId) as { n: number }).n;
  }

  test('region in-scope → permitted (queued)', async () => {
    const w = districtWorld();
    const res = await post(w.districtJwt, { scope: 'region', scope_ref: w.r1, format: 'csv', includes_sensitive: false });
    expect(res.status).toBe(202);
    expect((await res.json()).data.status).toBe('queued');
  });

  test('org scope → 403 + scope_violation', async () => {
    const w = districtWorld();
    expect((await post(w.districtJwt, { scope: 'org', scope_ref: null, format: 'csv' })).status).toBe(403);
    expect(violations(w.db, w.t.id)).toBe(1);
  });

  test('region out of scope → 403 + scope_violation', async () => {
    const w = districtWorld();
    expect((await post(w.districtJwt, { scope: 'region', scope_ref: w.r2, format: 'csv' })).status).toBe(403);
    expect(violations(w.db, w.t.id)).toBe(1);
  });

  test('includes_sensitive coerced to false (logged), export proceeds Standard-only', async () => {
    const w = districtWorld();
    const res = await post(w.districtJwt, { scope: 'region', scope_ref: w.r1, format: 'csv', includes_sensitive: true, reason: 'irrelevant for district' });
    expect(res.status).toBe(202); // proceeds
    const { data } = await res.json();
    expect(violations(w.db, w.t.id)).toBe(1); // the sensitive attempt was logged
    // the stored export row is Standard-only
    const tdb = new TenantDB(w.db, w.t.id);
    expect((tdb.get<{ includes_sensitive: number }>(`SELECT includes_sensitive FROM audit_exports WHERE tenant_id=? AND id=?`, [data.export_id]))!.includes_sensitive).toBe(0);
    // no export.sensitive_included audit was written
    expect(tdb.get(`SELECT id FROM audit_events WHERE tenant_id=? AND event_type='export.sensitive_included'`)).toBeUndefined();
    // worker generates a clean (no-Sensitive) artifact
    await processQueuedExports(w.db, NOW);
  });
});
