// Audit export CONTENT (Slice E) — the defensible, self-contained record for a scope:
// metadata header, current posture, requirements-in-force, the chronological event trail, and
// the documents manifest. Sensitive extracted values (full TIN, ACH account/routing) appear in
// the manifest ONLY when includesSensitive is true (Admin opt-in) — otherwise omitted entirely
// (the manifest still lists that the documents are on file).

import type Database from 'better-sqlite3';
import { TenantDB } from '@/lib/db/tenant';
import { inClause } from '@/lib/reports';
import { resolveRequirements, type Precedence } from '@/lib/requirements/resolver';
import { chaseExpiryByVendor } from '@/lib/notifications/chase';
import { decryptField } from '@/lib/crypto/field';
import { scopeAuditEvents, type ExportScope } from './audit-export';

const DAY = 86_400_000;

export interface AuditExportContent {
  metadata: { label: string; value: string }[];
  posture: { metric: string; value: string }[];
  requirements: { location: string; trade: string; requirement: string; required: string; source: string }[];
  events: { created_at: string; actor_type: string; actor_id: string; event_type: string; target_type: string; target_id: string; payload_json: string }[];
  documents: { vendor: string; doc_type: string; document_id: string; uploaded_at: string; state: string; sensitive: string }[];
}

interface ScopeSets { vendorIds: string[]; locationIds: string[] | null }

function scopeSets(db: Database.Database, tenantId: string, scope: ExportScope, scopeRef: string | null): ScopeSets {
  const tdb = new TenantDB(db, tenantId);
  if (scope === 'org' || scope === 'tenant_offboard') {
    return { vendorIds: tdb.all<{ id: string }>('SELECT id FROM vendors WHERE tenant_id = ?').map((r) => r.id), locationIds: null };
  }
  if (scope === 'vendor') {
    const locIds = tdb.all<{ location_id: string }>('SELECT location_id FROM vendor_locations WHERE tenant_id = ? AND vendor_id = ?', [scopeRef]).map((r) => r.location_id);
    return { vendorIds: scopeRef ? [scopeRef] : [], locationIds: locIds };
  }
  if (scope === 'location') {
    const vIds = tdb.all<{ vendor_id: string }>('SELECT DISTINCT vendor_id FROM vendor_locations WHERE tenant_id = ? AND location_id = ?', [scopeRef]).map((r) => r.vendor_id);
    return { vendorIds: vIds, locationIds: scopeRef ? [scopeRef] : [] };
  }
  // region
  const locIds = tdb.all<{ id: string }>('SELECT id FROM locations WHERE tenant_id = ? AND region_id = ?', [scopeRef]).map((r) => r.id);
  const vIds = locIds.length ? tdb.all<{ vendor_id: string }>(`SELECT DISTINCT vendor_id FROM vendor_locations WHERE tenant_id = ? AND location_id IN (${inClause(locIds)})`, locIds).map((r) => r.vendor_id) : [];
  return { vendorIds: vIds, locationIds: locIds };
}

export function gatherAuditExportContent(
  db: Database.Database,
  tenantId: string,
  input: { scope: ExportScope; scopeRef: string | null; includesSensitive: boolean; generatedAt: string; generator: { id: string; name: string; role: string } | null }
): AuditExportContent {
  const { scope, scopeRef, includesSensitive, generatedAt, generator } = input;
  const tdb = new TenantDB(db, tenantId);
  const tenant = db.prepare('SELECT name FROM tenants WHERE id = ?').get(tenantId) as { name: string } | undefined;
  const { vendorIds, locationIds } = scopeSets(db, tenantId, scope, scopeRef);

  // 1. Metadata header
  const metadata: AuditExportContent['metadata'] = [
    { label: 'Tenant', value: tenant?.name ?? tenantId },
    { label: 'Scope', value: scope + (scopeRef ? ` (${scopeRef})` : '') },
    { label: 'Generated at', value: generatedAt },
    { label: 'Generated by', value: generator ? `${generator.name} (${generator.role})` : 'system' },
    { label: 'Sensitive data included', value: includesSensitive ? 'YES' : 'no' },
  ];

  // 2. Posture (current vendor_location status counts for the scope)
  const locClause = locationIds === null ? '' : locationIds.length === 0 ? ' AND 1=0' : ` AND location_id IN (${inClause(locationIds)})`;
  const statusRows = tdb.all<{ status: string; n: number }>(
    `SELECT status, COUNT(*) AS n FROM vendor_locations WHERE tenant_id = ?${locClause} GROUP BY status`,
    locationIds ?? []
  );
  const counts: Record<string, number> = {};
  let total = 0;
  for (const r of statusRows) { counts[r.status] = r.n; total += r.n; }
  const expiryMap = chaseExpiryByVendor(db, tenantId);
  const now = Date.parse(generatedAt);
  const renewal90 = vendorIds.filter((v) => { const e = expiryMap.get(v); return e && Date.parse(e) - now <= 90 * DAY && Date.parse(e) - now >= 0; }).length;
  const posture: AuditExportContent['posture'] = [
    { metric: 'Compliant %', value: total > 0 ? `${Math.round(((counts['approved'] ?? 0) / total) * 1000) / 10}%` : 'n/a' },
    { metric: 'Approved', value: String(counts['approved'] ?? 0) },
    { metric: 'Under review', value: String(counts['under_review'] ?? 0) },
    { metric: 'Non-compliant', value: String(counts['non_compliant'] ?? 0) },
    { metric: 'Expired', value: String(counts['expired'] ?? 0) },
    { metric: 'Open exceptions', value: String((counts['under_review'] ?? 0) + (counts['non_compliant'] ?? 0) + (counts['expired'] ?? 0)) },
    { metric: 'Renewal exposure (next 90d)', value: String(renewal90) },
    { metric: 'Total vendor-locations in scope', value: String(total) },
  ];

  // 3. Requirements-in-force (resolved matrix per in-scope location × trade present there)
  const settings = tdb.get<{ precedence_policy: string }>('SELECT precedence_policy FROM requirement_settings WHERE tenant_id = ?');
  const precedence = (settings?.precedence_policy as Precedence) ?? 'strictest';
  const reqLocations = locationIds === null
    ? tdb.all<{ id: string; name: string }>(`SELECT id, name FROM locations WHERE tenant_id = ? AND status = 'active'`)
    : locationIds.length ? tdb.all<{ id: string; name: string }>(`SELECT id, name FROM locations WHERE tenant_id = ? AND id IN (${inClause(locationIds)})`, locationIds) : [];
  const requirements: AuditExportContent['requirements'] = [];
  for (const loc of reqLocations) {
    const trades = tdb.all<{ trade: string }>(
      `SELECT DISTINCT v.trade FROM vendor_locations vl JOIN vendors v ON v.id = vl.vendor_id AND v.tenant_id = vl.tenant_id WHERE vl.tenant_id = ? AND vl.location_id = ?`,
      [loc.id]
    ).map((r) => r.trade);
    for (const trade of trades) {
      const matrix = resolveRequirements(db, { tenantId, vendorTrade: trade, locationId: loc.id, precedence });
      for (const [key, entry] of Object.entries(matrix)) {
        requirements.push({ location: loc.name, trade, requirement: key, required: entry.required_value, source: entry.scope });
      }
    }
  }

  // 4. Chronological event trail
  const events = scopeAuditEvents(db, tenantId, scope, scopeRef).map((e) => ({
    created_at: e.created_at, actor_type: e.actor_type, actor_id: e.actor_id ?? '', event_type: e.event_type,
    target_type: e.target_type ?? '', target_id: e.target_id ?? '', payload_json: e.payload_json ?? '',
  }));

  // 5. Documents manifest (meta only by default; Sensitive values only when opted in)
  const documents: AuditExportContent['documents'] = [];
  for (const vid of vendorIds) {
    const vname = (tdb.get<{ business_name: string }>('SELECT business_name FROM vendors WHERE tenant_id = ? AND id = ?', [vid])?.business_name) ?? vid;
    const docs = tdb.all<{ id: string; doc_type: string; uploaded_at: string; state: string; superseded_by: string | null }>(
      'SELECT id, doc_type, uploaded_at, state, superseded_by FROM documents WHERE tenant_id = ? AND vendor_id = ? ORDER BY uploaded_at ASC',
      [vid]
    );
    for (const d of docs) {
      let sensitive = '';
      if (includesSensitive) sensitive = decryptedSensitiveFor(db, tenantId, d.id, d.doc_type);
      documents.push({
        vendor: vname, doc_type: d.doc_type, document_id: d.id, uploaded_at: d.uploaded_at,
        state: d.superseded_by ? 'superseded' : d.state, sensitive,
      });
    }
  }

  return { metadata, posture, requirements, events, documents };
}

/** Decrypt the Sensitive leaves (TIN for W-9, routing/account for ACH) for the manifest. */
function decryptedSensitiveFor(db: Database.Database, tenantId: string, documentId: string, docType: string): string {
  if (docType !== 'w9' && docType !== 'ach') return '';
  const tdb = new TenantDB(db, tenantId);
  const ex = tdb.get<{ payload_json: string }>('SELECT payload_json FROM extractions WHERE tenant_id = ? AND document_id = ? ORDER BY created_at DESC LIMIT 1', [documentId]);
  if (!ex) return '';
  try {
    const p = JSON.parse(ex.payload_json) as Record<string, { value?: string | null }>;
    const dec = (v?: string | null) => (v ? safeDecrypt(v) : '');
    if (docType === 'w9') return `TIN=${dec(p.tin_value?.value)}`;
    return `routing=${dec(p.routing_number?.value)} account=${dec(p.account_number?.value)}`;
  } catch {
    return '';
  }
}
function safeDecrypt(cipher: string): string {
  try { return decryptField(cipher); } catch { return '(unreadable)'; }
}
