// Audit export CONTENT (Slice E) — the defensible, self-contained record for a scope:
// metadata header, current posture, requirements-in-force, the chronological event trail, and
// the documents manifest. Sensitive extracted values (full TIN, ACH account/routing) appear in
// the manifest ONLY when includesSensitive is true (Admin opt-in) — otherwise omitted entirely
// (the manifest still lists that the documents are on file).

import type { Db } from '@/lib/db/client';
import { TenantDB } from '@/lib/db/tenant';
import { resolveRequirements, type Precedence } from '@/lib/requirements/resolver';
import { chaseExpiryByVendor } from '@/lib/notifications/chase';
import { decryptField } from '@/lib/crypto/field';
import { scopeAuditEvents, type ExportScope } from './audit-export';

const DAY = 86_400_000;

export interface SensitiveDecryptFailures { tin: number; routing: number; account: number }

export interface AuditExportContent {
  metadata: { label: string; value: string }[];
  posture: { metric: string; value: string }[];
  requirements: { location: string; trade: string; requirement: string; required: string; source: string }[];
  events: { created_at: string; actor_type: string; actor_id: string; event_type: string; target_type: string; target_id: string; payload_json: string }[];
  documents: { vendor: string; doc_type: string; document_id: string; uploaded_at: string; state: string; sensitive: string }[];
  /** Count of Sensitive leaves that could not be decrypted during a Sensitive-included build. */
  decryptFailures: SensitiveDecryptFailures;
}

interface ScopeSets { vendorIds: string[]; locationIds: string[] | null }

/**
 * Postgres-parameterized IN(...) placeholder list, starting at $<startAt>. `reports/index.ts`'s
 * `inClause()` is SQLite `?`-only (still Stage 9's file, un-converted) — a narrow local helper
 * here avoids pulling that whole not-yet-scoped file into this stage's conversion.
 */
function inClausePg(count: number, startAt: number): string {
  return Array.from({ length: count }, (_, i) => `$${startAt + i}`).join(', ');
}

async function scopeSets(db: Db, tenantId: string, scope: ExportScope, scopeRef: string | null): Promise<ScopeSets> {
  const tdb = new TenantDB(db, tenantId);
  if (scope === 'org' || scope === 'tenant_offboard') {
    return { vendorIds: (await tdb.all<{ id: string }>('SELECT id FROM vendors WHERE tenant_id = $1')).map((r) => r.id), locationIds: null };
  }
  if (scope === 'vendor') {
    const locIds = (await tdb.all<{ location_id: string }>('SELECT location_id FROM vendor_locations WHERE tenant_id = $1 AND vendor_id = $2', [scopeRef])).map((r) => r.location_id);
    return { vendorIds: scopeRef ? [scopeRef] : [], locationIds: locIds };
  }
  if (scope === 'location') {
    const vIds = (await tdb.all<{ vendor_id: string }>('SELECT DISTINCT vendor_id FROM vendor_locations WHERE tenant_id = $1 AND location_id = $2', [scopeRef])).map((r) => r.vendor_id);
    return { vendorIds: vIds, locationIds: scopeRef ? [scopeRef] : [] };
  }
  // region
  const locIds = (await tdb.all<{ id: string }>('SELECT id FROM locations WHERE tenant_id = $1 AND region_id = $2', [scopeRef])).map((r) => r.id);
  const vIds = locIds.length
    ? (await tdb.all<{ vendor_id: string }>(`SELECT DISTINCT vendor_id FROM vendor_locations WHERE tenant_id = $1 AND location_id IN (${inClausePg(locIds.length, 2)})`, locIds)).map((r) => r.vendor_id)
    : [];
  return { vendorIds: vIds, locationIds: locIds };
}

export async function gatherAuditExportContent(
  db: Db,
  tenantId: string,
  input: { scope: ExportScope; scopeRef: string | null; includesSensitive: boolean; generatedAt: string; generator: { id: string; name: string; role: string } | null }
): Promise<AuditExportContent> {
  const { scope, scopeRef, includesSensitive, generatedAt, generator } = input;
  const tdb = new TenantDB(db, tenantId);
  const tenantRow = await db.selectFrom('tenants').select('name').where('id', '=', tenantId).executeTakeFirst();
  const { vendorIds, locationIds } = await scopeSets(db, tenantId, scope, scopeRef);

  // 1. Metadata header
  const metadata: AuditExportContent['metadata'] = [
    { label: 'Tenant', value: tenantRow?.name ?? tenantId },
    { label: 'Scope', value: scope + (scopeRef ? ` (${scopeRef})` : '') },
    { label: 'Generated at', value: generatedAt },
    { label: 'Generated by', value: generator ? `${generator.name} (${generator.role})` : 'system' },
    { label: 'Sensitive data included', value: includesSensitive ? 'YES' : 'no' },
  ];

  // 2. Posture (current vendor_location status counts for the scope)
  const locClause = locationIds === null ? '' : locationIds.length === 0 ? ' AND 1=0' : ` AND location_id IN (${inClausePg(locationIds.length, 2)})`;
  const statusRows = await tdb.all<{ status: string; n: string }>(
    `SELECT status, COUNT(*) AS n FROM vendor_locations WHERE tenant_id = $1${locClause} GROUP BY status`,
    locationIds ?? []
  );
  const counts: Record<string, number> = {};
  let total = 0;
  for (const r of statusRows) { const n = Number(r.n); counts[r.status] = n; total += n; } // COUNT(*) is bigint-as-string (invariant 3)
  const expiryMap = await chaseExpiryByVendor(db, tenantId);
  const now = Date.parse(generatedAt);
  const renewal90 = vendorIds.filter((v) => { const e = expiryMap.get(v); return e && Date.parse(e) - now <= 90 * DAY && Date.parse(e) - now >= 0; }).length;
  const posture: AuditExportContent['posture'] = [
    { metric: 'Compliant %', value: total > 0 ? `${Math.round(((counts['approved'] ?? 0) / total) * 1000) / 10}%` : 'n/a' },
    { metric: 'Approved', value: String(counts['approved'] ?? 0) },
    { metric: 'Under review', value: String(counts['under_review'] ?? 0) },
    { metric: 'Non-compliant', value: String(counts['non_compliant'] ?? 0) },
    { metric: 'Expired', value: String(counts['expired'] ?? 0) },
    { metric: 'Open exceptions', value: String((counts['under_review'] ?? 0) + (counts['non_compliant'] ?? 0) + (counts['expired'] ?? 0)) },
    { metric: 'Renewal exposure (next 90d)', value: String(renewal90) },
    { metric: 'Total vendor-locations in scope', value: String(total) },
  ];

  // 3. Requirements-in-force (resolved matrix per in-scope location × trade present there)
  const settings = await tdb.get<{ precedence_policy: string }>('SELECT precedence_policy FROM requirement_settings WHERE tenant_id = $1');
  const precedence = (settings?.precedence_policy as Precedence) ?? 'strictest';
  const reqLocations = locationIds === null
    ? await tdb.all<{ id: string; name: string }>(`SELECT id, name FROM locations WHERE tenant_id = $1 AND status = 'active'`)
    : locationIds.length ? await tdb.all<{ id: string; name: string }>(`SELECT id, name FROM locations WHERE tenant_id = $1 AND id IN (${inClausePg(locationIds.length, 2)})`, locationIds) : [];
  const requirements: AuditExportContent['requirements'] = [];
  for (const loc of reqLocations) {
    const trades = (await tdb.all<{ trade: string }>(
      `SELECT DISTINCT v.trade FROM vendor_locations vl JOIN vendors v ON v.id = vl.vendor_id AND v.tenant_id = vl.tenant_id WHERE vl.tenant_id = $1 AND vl.location_id = $2`,
      [loc.id]
    )).map((r) => r.trade);
    for (const trade of trades) {
      const matrix = await resolveRequirements(db, { tenantId, vendorTrade: trade, locationId: loc.id, precedence });
      for (const [key, entry] of Object.entries(matrix)) {
        requirements.push({ location: loc.name, trade, requirement: key, required: entry.required_value, source: entry.scope });
      }
    }
  }

  // 4. Chronological event trail. payload_json comes back jsonb-parsed (invariant 2) — re-
  // stringified here deliberately: this is a rendered CSV/PDF text cell, not a live API
  // response, so the export needs the payload's JSON TEXT representation, not the object
  // itself (invariant 9's "read vs write boundary" distinction, not a violation of it).
  const eventRows = await scopeAuditEvents(db, tenantId, scope, scopeRef);
  const events = eventRows.map((e) => ({
    created_at: e.created_at, actor_type: e.actor_type, actor_id: e.actor_id ?? '', event_type: e.event_type,
    target_type: e.target_type ?? '', target_id: e.target_id ?? '', payload_json: e.payload_json ? JSON.stringify(e.payload_json) : '',
  }));

  // 5. Documents manifest (meta only by default; Sensitive values only when opted in)
  const documents: AuditExportContent['documents'] = [];
  const decryptFailures: SensitiveDecryptFailures = { tin: 0, routing: 0, account: 0 };
  for (const vid of vendorIds) {
    const vname = (await tdb.get<{ business_name: string }>('SELECT business_name FROM vendors WHERE tenant_id = $1 AND id = $2', [vid]))?.business_name ?? vid;
    const docs = await tdb.all<{ id: string; doc_type: string; uploaded_at: string; state: string; superseded_by: string | null }>(
      'SELECT id, doc_type, uploaded_at, state, superseded_by FROM documents WHERE tenant_id = $1 AND vendor_id = $2 ORDER BY uploaded_at ASC',
      [vid]
    );
    for (const d of docs) {
      let sensitive = '';
      if (includesSensitive) sensitive = await decryptedSensitiveFor(db, tenantId, d.id, d.doc_type, decryptFailures);
      documents.push({
        vendor: vname, doc_type: d.doc_type, document_id: d.id, uploaded_at: d.uploaded_at,
        state: d.superseded_by ? 'superseded' : d.state, sensitive,
      });
    }
  }

  return { metadata, posture, requirements, events, documents, decryptFailures };
}

/** Decrypt the Sensitive leaves (TIN for W-9, routing/account for ACH) for the manifest.
 *  Counts unreadable values per category into `fails` (the values themselves never leak). */
async function decryptedSensitiveFor(db: Db, tenantId: string, documentId: string, docType: string, fails: SensitiveDecryptFailures): Promise<string> {
  if (docType !== 'w9' && docType !== 'ach') return '';
  const tdb = new TenantDB(db, tenantId);
  const ex = await tdb.get<{ payload_json: Record<string, { value?: string | null }> }>(
    'SELECT payload_json FROM extractions WHERE tenant_id = $1 AND document_id = $2 ORDER BY created_at DESC LIMIT 1',
    [documentId]
  );
  if (!ex) return '';
  const p = ex.payload_json; // jsonb — already parsed, never JSON.parse() (invariant 2)
  const dec = (v: string | null | undefined, cat: keyof SensitiveDecryptFailures): string => {
    if (!v) return '';
    try { return decryptField(v); } catch { fails[cat]++; return '(unreadable)'; }
  };
  if (docType === 'w9') return `TIN=${dec(p['tin_value']?.value, 'tin')}`;
  return `routing=${dec(p['routing_number']?.value, 'routing')} account=${dec(p['account_number']?.value, 'account')}`;
}
